// avatar-workspace/src/libs/avatar-player/src/lib/components/avatar-player/avatar-player.component.ts
// libs/avatar-player/src/lib/components/avatar-player/avatar-player.component.ts
import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  signal,
  inject,
  NgZone,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import type { AvatarConfig } from '@avatar-workspace/avatar-shared';
import { LipSyncService } from '../../services/lip-sync.service';
import { SvgAvatarComponent } from '../svg-avatar/svg-avatar.component';

@Component({
  selector: 'app-avatar-player',
  standalone: true,
  imports: [CommonModule, SvgAvatarComponent],
  // Declared here so importing this standalone component is enough. Without it
  // a consumer that skips AvatarPlayerModule gets a NullInjectorError at
  // runtime rather than a compile error.
  providers: [LipSyncService],
  template: `
    <div class="avatar-player" [class.avatar-player--speaking]="speaking">
      <app-svg-avatar
        [config]="config"
        [animationsEnabled]="true"
        [viseme]="currentViseme()"
        [idsPrefix]="idsPrefix"
        [style.width.px]="displaySize()"
        [style.height.px]="displaySize()"
        class="player-avatar" />
    </div>
  `,
  styleUrl: './avatar-player.component.scss',
})
export class AvatarPlayerComponent implements OnChanges {
  @Input({ required: true }) config!: AvatarConfig;
  @Input() speaking = false;
  @Input() message = '';

  /**
   * Namespace for the generated `clipPath` ids.
   *
   * REQUIRED when more than one player is on a page. Every avatar emits
   * `url(#hat-clip)`, which resolves against the *first* matching element in
   * the document — so without a unique prefix per avatar they all clip against
   * whichever came first, and hats and helmets stop hiding hair.
   */
  @Input() idsPrefix = '';

  /** Base edge length in px. It grows while speaking. */
  @Input() size = 48;

  currentViseme = signal(0);

  private lipSync = inject(LipSyncService);
  private zone = inject(NgZone);
  private lipSyncCancelFn: (() => void) | null = null;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['speaking'] || changes['message']) {
      // Always cancel previous playback before starting new
      this.lipSyncCancelFn?.();

      if (this.speaking && this.message) {
        const visemes = this.lipSync.textToVisemes(this.message);
        this.lipSyncCancelFn = this.lipSync.play(visemes, (v) => {
          this.zone.run(() => this.currentViseme.set(v));
        });
      } else {
        this.currentViseme.set(0);
      }
    }
  }

  /** Speaking reads as a small "leaning in", so the avatar grows. */
  displaySize(): number {
    return this.speaking ? this.size * 1.5 : this.size;
  }
}

// src/libs/avatar-player-react/src/avatar-player.tsx
import { SvgAvatar } from './svg-avatar';
import { useLipSync } from './use-lip-sync';
import type { AvatarConfig } from '../../avatar-player/src/lib/geometry';

export interface AvatarPlayerProps {
  config: AvatarConfig;
  /** Mouth the `message` while true. */
  speaking?: boolean;
  /** Text to mouth. Ignored unless `speaking` is true. */
  message?: string;
  /**
   * Namespace for generated element ids.
   *
   * REQUIRED when more than one player is on a page — see `SvgAvatar`. In React
   * this matters more than in Angular, because React reuses DOM nodes when a
   * list re-renders: without a stable prefix, a recycled node can keep the
   * previous avatar's `url(#hat-clip)` target.
   */
  idsPrefix?: string;
  /** Base edge length in px. It grows while speaking. */
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * Drop-in animated avatar: blinking, eye movement, head idle motion and lip
 * sync.
 *
 * Mirrors the Angular `AvatarPlayerComponent` prop for prop, and shares its
 * renderer and animation logic from the shared geometry — the only
 * difference is the framework syntax.
 *
 * Sizes itself inline from `size`, so a consumer can drop a player at any scale
 * without fighting a stylesheet.
 */
export function AvatarPlayer({
  config,
  speaking = false,
  message = '',
  idsPrefix = '',
  size = 48,
  className,
  style,
}: AvatarPlayerProps) {
  const viseme = useLipSync({ speaking, message });

  /** Speaking reads as a small "leaning in", so the avatar grows. */
  const displaySize = speaking ? size * 1.5 : size;

  const classes = ['avatar-player'];
  if (speaking) classes.push('avatar-player--speaking');
  if (className) classes.push(className);

  return (
    <div className={classes.join(' ')} style={style}>
      <SvgAvatar
        config={config}
        animationsEnabled
        animated
        viseme={viseme}
        idsPrefix={idsPrefix}
        className="player-avatar"
        width={displaySize}
        height={displaySize}
      />
    </div>
  );
}
